#!/usr/bin/env node
// scripts/live-demos.js
// ═══════════════════════════════════════════════════════════════════════
// LIVE DEMO SUITE — 5 scenarios against ChangeLens's own codebase
//
// Each scenario simulates a realistic PR and runs the full pipeline
// with real import graph traversal — dogfooding our own tool.
//
// Run: node scripts/live-demos.js
// ═══════════════════════════════════════════════════════════════════════

import { analyze } from "../src/index.js";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(__dirname, "..");

const DEMOS = [
  // ── DEMO 1: Core module export signature change ────────────────
  {
    name: "Core parser export change",
    description: "Developer adds an options parameter to parseDiff",
    prId: "PR-101",
    diff: `diff --git a/src/core/diffParser.js b/src/core/diffParser.js
index abc1234..def5678 100644
--- a/src/core/diffParser.js
+++ b/src/core/diffParser.js
@@ -10,5 +10,7 @@
-export function parseDiff(diffText) {
+export function parseDiff(diffText, opts = {}) {
+  const { strict = false } = opts;
   // existing logic
 }`,
  },

  // ── DEMO 2: Output formatter — leaf change ─────────────────────
  {
    name: "PR comment formatter tweak",
    description: "Updating the footer text — no consumers outside output/",
    prId: "PR-102",
    diff: `diff --git a/src/output/prCommentFormatter.js b/src/output/prCommentFormatter.js
index abc1234..def5678 100644
--- a/src/output/prCommentFormatter.js
+++ b/src/output/prCommentFormatter.js
@@ -99,4 +99,4 @@
-  lines.push(\`<sub>Generated by ChangeLens · Static analysis impact estimate · Scope: import graph + surface heuristics · Not a guarantee</sub>\`);
+  lines.push(\`<sub>Generated by ChangeLens v0.1.0 · Static analysis · Not a guarantee</sub>\`);`,
  },

  // ── DEMO 3: Test-only change (should be LOW) ───────────────────
  {
    name: "New test file only",
    description: "Adding a new regression test — should be LOW risk",
    prId: "PR-103",
    diff: `diff --git a/tests/new_regression.test.js b/tests/new_regression.test.js
new file mode 100644
index 0000000..abc1234
--- /dev/null
+++ b/tests/new_regression.test.js
@@ -0,0 +1,15 @@
+import { parseDiff } from '../src/core/diffParser.js';
+import { describe, it } from 'node:test';
+import assert from 'node:assert/strict';
+
+describe('regression: rename detection', () => {
+  it('detects pure renames', () => {
+    const diff = \`diff --git a/old.js b/new.js
+similarity index 100%
+rename from old.js
+rename to new.js\`;
+    const result = parseDiff(diff);
+    assert.equal(result[0].status, 'renamed');
+  });
+});`,
  },

  // ── DEMO 4: Blast radius logic change with consumers ───────────
  {
    name: "Blast radius scoring refactor",
    description: "Modifying the risk weight calculation — index.js depends on this",
    prId: "PR-104",
    diff: `diff --git a/src/core/blastRadius.js b/src/core/blastRadius.js
index abc1234..def5678 100644
--- a/src/core/blastRadius.js
+++ b/src/core/blastRadius.js
@@ -5,8 +5,12 @@
-export function calculateBlastRadius(classifications, consumerMap, fileChanges) {
+export function calculateBlastRadius(classifications, consumerMap, fileChanges, options = {}) {
+  const { weightOverrides = {} } = options;
   const evidence = [];
   let maxWeight = 0;
+  if (Object.keys(weightOverrides).length > 0) {
+    console.log('[blast] using custom weights');
+  }
   return evidence;
 }`,
  },

  // ── DEMO 5: Multi-file cosmetic change ─────────────────────────
  {
    name: "Comment cleanup across core modules",
    description: "Cleaning up comments across 3 files — should be LOW",
    prId: "PR-105",
    diff: `diff --git a/src/core/diffParser.js b/src/core/diffParser.js
index abc1234..def5678 100644
--- a/src/core/diffParser.js
+++ b/src/core/diffParser.js
@@ -1,4 +1,4 @@
-// src/core/diffParser.js
+// src/core/diffParser.js — Unified diff parser

diff --git a/src/core/graphWalker.js b/src/core/graphWalker.js
index abc1234..def5678 100644
--- a/src/core/graphWalker.js
+++ b/src/core/graphWalker.js
@@ -1,4 +1,4 @@
-// src/core/graphWalker.js
+// src/core/graphWalker.js — Import graph BFS traversal

diff --git a/src/core/surfaceClassifier.js b/src/core/surfaceClassifier.js
index abc1234..def5678 100644
--- a/src/core/surfaceClassifier.js
+++ b/src/core/surfaceClassifier.js
@@ -1,4 +1,4 @@
-// src/core/surfaceClassifier.js
+// src/core/surfaceClassifier.js — Surface category classifier`,
  },
];

// ── RUN ───────────────────────────────────────────────────────────────

console.log("╔══════════════════════════════════════════════════════════════╗");
console.log("║         ChangeLens — Live Demo Suite (5 scenarios)          ║");
console.log("║         Target: ChangeLens (self-referential dogfood)       ║");
console.log("╚══════════════════════════════════════════════════════════════╝\n");

const results = [];

for (const demo of DEMOS) {
  console.log(`${"═".repeat(64)}`);
  console.log(`  DEMO: ${demo.name}`);
  console.log(`  ${demo.description}`);
  console.log(`${"═".repeat(64)}\n`);

  const { card, markdown } = analyze(demo.diff, PROJECT_ROOT, { prId: demo.prId });

  console.log(markdown);
  console.log();

  results.push({
    name: demo.name,
    prId: demo.prId,
    riskTier: card.riskTier,
    consumers: card.affectedConsumers.length,
    surfaces: card.changedSurfaces.length,
    safeToMerge: card.safeToMerge,
    evidence: card.evidence.length,
  });
}

// ── SUMMARY TABLE ─────────────────────────────────────────────────────

console.log(`\n${"═".repeat(64)}`);
console.log("  RESULTS MATRIX");
console.log(`${"═".repeat(64)}\n`);

console.log("  PR       | Risk   | Consumers | Safe? | Scenario");
console.log("  ─────────┼────────┼───────────┼───────┼─────────────────────");
for (const r of results) {
  const badge = { LOW: "🟢", MEDIUM: "🟡", HIGH: "🔴" }[r.riskTier];
  console.log(`  ${r.prId.padEnd(9)}| ${badge} ${r.riskTier.padEnd(5)}| ${String(r.consumers).padEnd(10)}| ${r.safeToMerge ? "✅" : "⚠️ "}   | ${r.name}`);
}
console.log();
